name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  NODE_ENV: test

jobs:
  validate:
    name: Validate Build and Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16, 18, 20]
      fail-fast: false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
      
      - name: Install dependencies
        run: |
          cd server
          npm ci --prefer-offline --no-audit
      
      - name: TypeScript type checking
        run: |
          cd server
          npm run typecheck
      
      - name: Build project
        run: |
          cd server
          npm run build
      
      - name: Run tests
        run: |
          cd server
          npm test
        timeout-minutes: 5
      
      - name: Validate MCP server startup (Unix)
        if: runner.os != 'Windows'
        run: |
          cd server
          # Use a cross-platform timeout approach
          if command -v timeout >/dev/null 2>&1; then
            timeout 10s npm run start:debug || true
            if [ $? -eq 124 ]; then
              echo "✅ Server startup timeout (expected)"
            else
              echo "❌ Server startup failed"
              exit 1
            fi
          elif command -v gtimeout >/dev/null 2>&1; then
            # macOS with coreutils installed
            gtimeout 10s npm run start:debug || true
            if [ $? -eq 124 ]; then
              echo "✅ Server startup timeout (expected)"
            else
              echo "❌ Server startup failed"
              exit 1
            fi
          else
            # Fallback: use background process with sleep
            npm run start:debug &
            server_pid=$!
            sleep 10
            if kill -0 $server_pid 2>/dev/null; then
              echo "✅ Server startup timeout (expected)"
              kill $server_pid 2>/dev/null || true
            else
              echo "❌ Server startup failed"
              exit 1
            fi
          fi
      
      - name: Validate MCP server startup (Windows)
        if: runner.os == 'Windows'
        run: |
          cd server
          $job = Start-Job -ScriptBlock { npm run start:debug }
          Start-Sleep -Seconds 10
          Stop-Job $job
          Remove-Job $job
          Write-Host "✅ Server startup timeout (expected)"
        shell: powershell
      
      - name: Upload build artifacts
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            server/dist/
            server/package.json
            server/package-lock.json
          retention-days: 7

  cageerf-integration:
    name: CAGEERF Framework Integration Tests
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
      
      - name: Install dependencies
        run: |
          cd server
          npm ci --prefer-offline --no-audit
      
      - name: Build project
        run: |
          cd server
          npm run build
      
      - name: Validate CAGEERF Analyzer Module
        run: |
          cd server
          node -e "
            const analyzer = require('./dist/utils/cageerf-analyzer.js');
            console.log('✅ CAGEERF Analyzer module loaded successfully');
            console.log('Available exports:', Object.keys(analyzer));
          "
      
      - name: Validate Template Generator
        run: |
          cd server
          node -e "
            const generator = require('./dist/utils/template-generator.js');
            console.log('✅ Template Generator module loaded successfully');
            console.log('Available exports:', Object.keys(generator));
          "
      
      - name: Validate Template Repository
        run: |
          cd server
          node -e "
            const repository = require('./dist/utils/template-repository.js');
            console.log('✅ Template Repository module loaded successfully');
            console.log('Available exports:', Object.keys(repository));
          "
      
      - name: Validate Enhanced Semantic Analyzer
        run: |
          cd server
          node -e "
            const analyzer = require('./dist/utils/semanticAnalyzer.js');
            console.log('✅ Enhanced Semantic Analyzer module loaded successfully');
            console.log('Available exports:', Object.keys(analyzer));
          "

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
      
      - name: Install dependencies
        run: |
          cd server
          npm ci --prefer-offline --no-audit
      
      - name: Check for sensitive files
        run: |
          if find . -name "*.env*" -o -name "*.key" -o -name "*.pem" -o -name "*.p12" | grep -v node_modules | grep -q .; then
            echo "❌ Sensitive files found in repository"
            find . -name "*.env*" -o -name "*.key" -o -name "*.pem" -o -name "*.p12" | grep -v node_modules
            exit 1
          else
            echo "✅ No sensitive files found"
          fi
      
      - name: Validate TypeScript files
        run: |
          cd server
          find src -name "*.ts" -exec echo "Checking {}" \;
          if find src -name "*.js" | grep -q .; then
            echo "❌ JavaScript files found in TypeScript source directory"
            find src -name "*.js"
            exit 1
          else
            echo "✅ All source files are TypeScript"
          fi
      
      - name: Check package.json consistency
        run: |
          cd server
          if npm ls --depth=0 >/dev/null 2>&1; then
            echo "✅ Package.json dependencies are consistent"
          else
            echo "❌ Package.json dependency issues found"
            npm ls --depth=0 || true
            exit 1
          fi
      
      - name: Validate build artifacts
        run: |
          cd server
          npm run build
          if [ -d "dist" ] && [ -f "dist/index.js" ]; then
            echo "✅ Build artifacts generated successfully"
          else
            echo "❌ Build artifacts missing"
            ls -la dist/ || echo "dist directory not found"
            exit 1
          fi